# Generated by Django 5.2.7 on 2025-11-12 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('factor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('telephone', models.CharField(max_length=15)),
                ('email_contacto', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_sec', models.IntegerField()),
                ('huella', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eco_Tracker.item')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eco_Tracker.clientes')),
            ],
        ),
    ]
